language: python

dist: focal

jobs:
  include:
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.9"
      env: TOXENV=py39
    - python: "3.10"
      env: TOXENV=py310
    - python: "3.11"
      env: TOXENV=py311
    - python: "3.12"
      env: TOXENV=py312
    - python: "3.13"
      env: TOXENV=py313
    - env: TOXENV=lint

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  coveralls
