import __future__ as _future
import struct as struct

from .base import Type as Type, _Buffer as _Buffer

absolute_import: _future._Feature

class Epub(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Zip(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Tar(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Rar(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Gz(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Bz2(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class SevenZ(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Pdf(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Exe(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Swf(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Rtf(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Nes(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Crx(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Cab(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Eot(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Ps(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Xz(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Sqlite(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Deb(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Ar(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Z(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Lzop(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Lz(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Elf(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Lz4(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Br(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Dcm(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Rpm(Type):
    MIME: str
    EXTENSION: str
    def __init__(self) -> None: ...
    def match(self, buf: _Buffer) -> bool: ...

class Zstd(Type):
    MIME: str
    EXTENSION: str
    MAGIC_SKIPPABLE_START: int
    MAGIC_SKIPPABLE_MASK: int
    def __init__(self) -> None: ...
    @staticmethod
    def _to_little_endian_int(buf: _Buffer) -> int: ...
    def match(self, buf: _Buffer) -> bool: ...
