# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  release_test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: ["3.12", "3.13"]
        include:
          - os: macos-latest
            python-version: '3.13'
          - os: windows-latest
            python-version: '3.13'

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Upgrade PIP
      run: python -m pip install --upgrade pip

    - name: Install application with ML
      run: python -m pip install .

    - name: CLI tool check
      run: filetype --help

    - name: Install test framework dependencies
      run: python -m pip install tox

    - name: Run tox pipeline
      run: tox

    - name: HTML coverage reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage_${{ matrix.python-version }}
        path: coverage
